field: 9b271a30-441e-4349-8015-e145efbaf982 # Content
fieldLayouts:
  53d7b82f-9f88-4144-8f1c-6df2e73eb55f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 456fe963-8095-43f7-9ac7-004950cdb04c # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 354c7547-6994-45ad-8475-0e09c8d13919
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ff440e52-0b0a-443c-9e55-f189c7170f0c # Hours
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68994a10-fde3-4061-9b81-c2f5e668ea41
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d3e4baf-1dfc-4231-b10d-9547b2b862af # Vakken
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 465247e4-7dd7-456b-9b92-643b3a3cb92c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1c08e99f-d363-4f85-ac44-674a466a509c
        userCondition: null
fields:
  0d3e4baf-1dfc-4231-b10d-9547b2b862af: # Vakken
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: vakkenField
    instructions: null
    name: Vakken
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      sources:
        - 'section:ceb21329-439a-4697-8cb3-c475786b9a24' # Vakken
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  456fe963-8095-43f7-9ac7-004950cdb04c: # Title
    columnSuffix: wkvskckq
    contentColumnType: text
    fieldGroup: null
    handle: titleField
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ff440e52-0b0a-443c-9e55-f189c7170f0c: # Hours
    columnSuffix: jrjxbtgu
    contentColumnType: text
    fieldGroup: null
    handle: hoursField
    instructions: null
    name: Hours
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: courseBlock
name: LessenTabel
sortOrder: 4
