field: 9b271a30-441e-4349-8015-e145efbaf982 # Content
fieldLayouts:
  ba4d769b-5987-4603-b24b-ef95e86161c6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d7e5facb-1764-45e8-adf6-9ba20f28fb29 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9d414a0-aeb7-4ddb-8946-23d24daffecd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 91e843ba-7864-4d13-bb71-8ce76d724096
        userCondition: null
fields:
  d7e5facb-1764-45e8-adf6-9ba20f28fb29: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageField
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:77447950-c8b4-43fe-b1cf-a08e5a9c48f6' # Icons
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:bbdd6a96-72b4-4202-9064-22f8072dd476' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: imageBlock
name: Image
sortOrder: 3
