field: e8812d57-0133-4e50-b012-346e92b6d39b
fieldLayouts:
  b4814d07-37f7-48d3-9ea0-0e73be3d7447:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 26a49e9f-6351-40e2-93ee-b7f4cf73da89 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c00a815c-8fe2-4c7a-8cf9-2a04f4ed86bf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b0b8c0f4-240f-4fa9-83c9-47278af412bd
        userCondition: null
fields:
  26a49e9f-6351-40e2-93ee-b7f4cf73da89: # Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: mxLink
    instructions: null
    name: Link
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
handle: linkBlock
name: Link
sortOrder: 2
