field: 9b271a30-441e-4349-8015-e145efbaf982 # Content
fieldLayouts:
  2d83dd7b-aa43-43fc-9600-eb897880d37a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3ae527fa-59b2-4c00-91d8-f4f595d8e1f5 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c39c228b-767e-4cab-b43b-6f1d7dbfdb5e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7e90748e-7700-4c89-84d2-2588f0b1e8e3
        userCondition: null
fields:
  3ae527fa-59b2-4c00-91d8-f4f595d8e1f5: # Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkField
    instructions: null
    name: Link
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: true
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
handle: linkBlock
name: Link
sortOrder: 2
