field: ed21da8b-8c14-467f-a3b1-acc785ca6cde # Numbers
fieldLayouts:
  1f6c37b2-9174-4151-aff4-5852133793d5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 38587038-2595-4982-aa29-d71c2cfe7a49 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3410b461-08f8-4570-8ecb-50f5f3f23d2d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85defccc-d047-4c0f-b17d-5a1c382cde52 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8017973-d072-4f82-960c-6135d33ba49a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aac60a40-7152-4a58-aa77-a339451ff4bd # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06c2f328-dcda-4428-9fba-ba8ec822584c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 282e08de-73d8-4ddb-a8cb-96f124541714
        userCondition: null
fields:
  85defccc-d047-4c0f-b17d-5a1c382cde52: # Title
    columnSuffix: vydjecvc
    contentColumnType: text
    fieldGroup: null
    handle: commonTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  38587038-2595-4982-aa29-d71c2cfe7a49: # Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: commonIcon
    instructions: null
    name: Icon
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:77447950-c8b4-43fe-b1cf-a08e5a9c48f6' # Icons
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:77447950-c8b4-43fe-b1cf-a08e5a9c48f6' # Icons
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  aac60a40-7152-4a58-aa77-a339451ff4bd: # Subtitle
    columnSuffix: wiybwugw
    contentColumnType: text
    fieldGroup: null
    handle: commonSubtitle
    instructions: null
    name: Subtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: numberBlock
name: Number
sortOrder: 1
