field: e8812d57-0133-4e50-b012-346e92b6d39b
fieldLayouts:
  9bc89364-a631-4a77-a93d-f7da365cfcb7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a384c360-0211-405c-84b8-af18769cddfe # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7b00285-587a-4bca-8d19-ed869af986c5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1d24158b-e55a-421f-b2d1-c2dd64789648
        userCondition: null
fields:
  a384c360-0211-405c-84b8-af18769cddfe: # Title
    columnSuffix: augloxkm
    contentColumnType: text
    fieldGroup: null
    handle: mxTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: titleBlock
name: Title
sortOrder: 1
