fieldLayouts:
  a62de82d-1121-4a4b-80a1-ddb9306e5181:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8d530b8d-a23a-4216-b51b-9faed21d58dc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 91da989b-aca3-4a36-a126-0f3223887bd4 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89e08a4b-03a3-47c9-89df-02735827b4d2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 42def604-6800-4588-8a73-5991539a3e96 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60310a20-1807-4db2-9bac-9503b766d000
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 497bf133-da9a-480b-8776-1b622fd6e2d7 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee9d92a9-f8cb-4f43-b9f1-e186065410c2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b02ac359-d1ee-4107-a6cb-18305753f0ab # Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d9922ca-6681-492d-ac5b-bc9e1c077330
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8ba16a85-331a-410c-8553-65a768c0a51e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: adc583d2-65c2-4163-99ea-8cb6887d5fb5 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e109a800-be7a-46c9-b96c-13c914b4324d
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 34e818da-8f00-43a9-8b9d-932780449a1f
        userCondition: null
handle: cards_default
hasTitleField: false
name: Default
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{commonTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
