fieldLayouts:
  24afdde1-a080-47d8-977b-cff010c14f89:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 18053e42-e3ba-4c8a-83b0-2d7cf0b880af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c55ccb24-d933-47a8-bad8-09f6949a6012 # Thumbmnail Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85a2ceae-3aa7-4c40-b21c-250a2db22c8b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 42def604-6800-4588-8a73-5991539a3e96 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 753711e6-dd6e-41e4-ad73-ea94ada484b3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1361e7f7-f9a4-41c7-a9a2-da753572f7ac # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ad9e238-9b79-4633-97a4-c6e21c14f49a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4c51cda2-a78f-4eff-89e7-9ce8b1141adb
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: 02b050d6-0241-4838-874e-64d1972ca179 # Album
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{commonTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
