fieldLayouts:
  eafb672b-9231-4d8d-8373-56b686d3dc81:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e994e265-baa6-4f26-9d99-640671b1cebb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 42def604-6800-4588-8a73-5991539a3e96 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d70d3ee-cda7-4fa7-8337-4faa421249ac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f9c35266-6925-4ac5-b80c-3adc5631e970 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0964490-c079-4c1d-b617-411bc26f5126
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e5ae2880-f1cd-46f5-aeab-f75fdf5b517c
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: ceb21329-439a-4697-8cb3-c475786b9a24 # Vakken
sortOrder: 1
titleFormat: '{commonTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
