fieldLayouts:
  286f0144-3959-4b17-b041-232dbcd6bacc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 889178d3-06e2-4ac8-b071-29e720d0f09c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 42def604-6800-4588-8a73-5991539a3e96 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87bf5961-4ea8-444a-9530-ef433c9073af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b02ac359-d1ee-4107-a6cb-18305753f0ab # Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6766db3-027c-4fab-8ac7-731837e96666
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: adc583d2-65c2-4163-99ea-8cb6887d5fb5 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db63fc93-2d5f-4918-8ca1-007c32b80668
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ab70b1eb-f480-4d3e-aa2b-94e1cd63c227
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: 1ca3d924-ca88-4ab1-a17f-80eba45b750b # NavColumns
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{commonTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
