fieldLayouts:
  2afbe5db-877f-4257-ab79-83ed2d5b718d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ecc0e066-d1b8-482d-9b3c-da66502d0989
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 42def604-6800-4588-8a73-5991539a3e96 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e057dd88-fdda-4f95-a748-535c8f1572ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f9c35266-6925-4ac5-b80c-3adc5631e970 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87b66443-8bb0-494f-805f-ec92a58aedbd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 497bf133-da9a-480b-8776-1b622fd6e2d7 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ac5e3c3-df5a-4cd1-ad91-a8f199a8cc32
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3fed10c6-640f-4012-aff1-a5a914e2e3ad # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f90bbcd-0dd8-4620-83e7-461090e9ff5c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 019d1715-8631-4856-a8cd-6e86fd1c34ba
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: e0199469-522e-4e9c-8fd4-33a017c3b94a # Quotes
sortOrder: 1
titleFormat: '{commonTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
