fieldLayouts:
  690dde37-222b-44fd-804b-7814dbf5f979:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 42def604-6800-4588-8a73-5991539a3e96 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc14d4ab-45d9-458b-ae39-8bd78c222e6e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 409f2f02-3965-4be8-bd7b-92b48cfe34ea # Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9158643a-2929-40ad-b5c1-42aa466172b6
            userCondition: null
            warning: null
            width: 100
        name: Block
        uid: 3e7c9ef9-baf6-477e-a7fd-fa3d1334e83f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2de925e3-f1b3-474f-aa3a-8917dc160d67 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06caf31b-71ef-4187-89cb-a22e00eea45c
            userCondition: null
            warning: null
            width: 100
        name: Body
        uid: 3c61fc98-484b-4fa1-b9ee-11d7dbe45c42
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c26ebda7-25da-46e8-83bd-694801cdd6c7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 448a95a7-11b0-4e1d-be6d-de1a71852362 # Seo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 112e0176-9f8f-4bcd-993a-c7957d08de39
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: b8220d42-ee66-4cc7-90bd-974b4a5d5dd2
        userCondition: null
handle: evenementen_default
hasTitleField: false
name: Default
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{commonTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
