color: null
description: null
fieldLayouts:
  524b1e20-2cf0-4dfa-a81d-982ee687b957:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 7588a71d-ca00-4f47-aff6-6663ee33ffd3 # Links - Link - Link
            handle: page
            includeInCards: false
            instructions: null
            label: Link
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b753d51-a14a-4d55-8fb6-7843ebfa872c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: be60d0fb-a29d-431e-8119-1a9c478c85bf
            handle: null
            includeInCards: true
            instructions: null
            label: Color
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 302e2e99-ed2d-4289-8166-60a261e248c0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 210e2463-d211-4462-b4f3-0b5bd9d1b2e4
        userCondition: null
handle: linkBlock3
hasTitleField: false
icon: null
name: Link
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
