color: null
description: null
fieldLayouts:
  2d83dd7b-aa43-43fc-9600-eb897880d37a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 3ae527fa-59b2-4c00-91d8-f4f595d8e1f5 # Content - Link - Link
            handle: null
            includeInCards: false
            instructions: null
            label: Link
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c39c228b-767e-4cab-b43b-6f1d7dbfdb5e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7e90748e-7700-4c89-84d2-2588f0b1e8e3
        userCondition: null
handle: linkBlock
hasTitleField: false
icon: null
name: Link
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
