fieldLayouts:
  2c1aa668-0604-4bc1-8332-8205ac7e2198:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ed7684e3-b6db-4d68-bb59-bfd9a45d3989
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 42def604-6800-4588-8a73-5991539a3e96 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a8de355-1120-4a65-93d3-9c189ef70dc5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3fed10c6-640f-4012-aff1-a5a914e2e3ad # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89c1b07d-4268-49e1-8f88-cb26230aa5b5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b271a30-441e-4349-8015-e145efbaf982 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24b8a7a6-a33f-4166-8a47-99316c238f73
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7bec2893-4d69-467b-ab34-ce052928a810
        userCondition: null
handle: tab_default
hasTitleField: false
name: Default
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{commonTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
