childBlocks: null
conditions: null
description: null
enabled: true
field: 2de925e3-f1b3-474f-aa3a-8917dc160d67 # Body
group: 06936d40-6287-4cf0-9565-4ea06bbc5f23 # Body
groupChildBlockTypes: true
handle: blogBlocks
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Blogs
sortOrder: 6
topLevel: true
