childBlocks: null
conditions: null
description: ''
enabled: true
field: 2de925e3-f1b3-474f-aa3a-8917dc160d67 # Body
fieldLayouts:
  8ec1edb2-c496-40b2-bd08-1712088e9890:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 42def604-6800-4588-8a73-5991539a3e96 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 316d6eca-156f-4e02-b165-7070b7a2a05b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 356fedab-a40b-492a-aeb5-a14c954d468a # Cards
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b9718b5-7ac9-4595-8f0e-4bec18a2e2d3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4c2e9207-ffcd-480c-9dba-9c4efa855d45
        userCondition: null
group: null
groupChildBlockTypes: true
handle: cardsBlock
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Cards
sortOrder: 3
topLevel: true
