childBlocks: null
conditions: null
description: ''
enabled: true
field: 2de925e3-f1b3-474f-aa3a-8917dc160d67 # Body
fieldLayouts:
  ad34cb5d-9fc8-4666-b376-dc0c7a4d8090:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 42def604-6800-4588-8a73-5991539a3e96 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 316d6eca-156f-4e02-b165-7070b7a2a05b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 356fedab-a40b-492a-aeb5-a14c954d468a # Cards
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b9718b5-7ac9-4595-8f0e-4bec18a2e2d3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4c2e9207-ffcd-480c-9dba-9c4efa855d45
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: adae52e8-4cf6-4f0e-ae1d-05059dbf611f # Background grey
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7eb611e5-aca5-489b-a86b-f065a7f41488
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6b8353f0-638c-4bdf-be1b-94ec215f6520 # No spacing top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab7d3943-e718-4091-9895-ff1e6fca6b50
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 714e96a6-9fba-4c90-8397-5dd0e0bfbf69
        userCondition: null
group: null
groupChildBlockTypes: true
handle: cardsBlock
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Cards
sortOrder: 2
topLevel: true
