childBlocks: null
conditions: null
description: ''
enabled: true
field: 5994f1c4-513f-444d-98dd-a5a111b1b594 # Footer column
fieldLayouts:
  a9da5c4f-386a-4e76-9d66-6864774608ac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 42def604-6800-4588-8a73-5991539a3e96 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d67efab-4ab3-4bcf-ab8f-6d812b77c587
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b02ac359-d1ee-4107-a6cb-18305753f0ab # Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc874070-cde6-44eb-a201-a4f51bafaa8f
            userCondition: null
            warning: null
            width: 100
        name: Column
        uid: b49bcf9c-d3d7-4eeb-9c32-5a6d4cde7117
        userCondition: null
group: null
groupChildBlockTypes: true
handle: column
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Column
topLevel: true
