childBlocks: null
conditions: null
description: ''
enabled: true
field: 2de925e3-f1b3-474f-aa3a-8917dc160d67 # Body
fieldLayouts:
  1c801d33-60cf-4a5b-ad4b-b298948aa6d4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 42def604-6800-4588-8a73-5991539a3e96 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc181619-c526-44c2-bb37-699b4fb6dcaa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b271a30-441e-4349-8015-e145efbaf982 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae332d4a-0a0d-428a-a697-a1cc61be9785
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3fed10c6-640f-4012-aff1-a5a914e2e3ad # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 061bbd2b-889f-4cf6-8f36-901692a90537
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: de2cecc7-7e32-4435-b701-e931b8a3fcb5
        userCondition: null
group: 06936d40-6287-4cf0-9565-4ea06bbc5f23 # Body
groupChildBlockTypes: true
handle: contactBlock
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Contact
topLevel: true
