childBlocks: null
conditions: null
description: ''
enabled: true
field: 2de925e3-f1b3-474f-aa3a-8917dc160d67 # Body
fieldLayouts:
  329ba948-b142-41d9-b03e-3723c064e2fc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 42def604-6800-4588-8a73-5991539a3e96 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52abc214-f616-4087-9aa2-46ef6f1e4a95
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 497bf133-da9a-480b-8776-1b622fd6e2d7 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3308ab9-f246-4ead-934e-53458169a321
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1361e7f7-f9a4-41c7-a9a2-da753572f7ac # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d929f90f-9cd9-487e-ab49-9d33c15242ee
            userCondition: null
            warning: null
            width: 100
        name: General
        uid: f07ca06f-1a2f-476a-951c-69377c3cc368
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: adc583d2-65c2-4163-99ea-8cb6887d5fb5 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 784ab6d7-4b95-4eb2-b207-f7f027b85965
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0a6ae889-cd44-4836-90c7-7eb4a7137ec5 # No spacing bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea7cb50d-941c-4c33-bd40-6677288dc02c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6b8353f0-638c-4bdf-be1b-94ec215f6520 # No spacing top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a777b949-cfc6-4ffa-b939-1e22d7438b62
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 9a55f4dd-4a39-4cef-97e1-12c678bde1e6
        userCondition: null
group: 06936d40-6287-4cf0-9565-4ea06bbc5f23 # Body
groupChildBlockTypes: true
handle: ctaBlock
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Cta
topLevel: true
