childBlocks: null
conditions: null
description: ''
enabled: true
field: 2de925e3-f1b3-474f-aa3a-8917dc160d67 # Body
fieldLayouts:
  5ea408ec-f0c5-4945-81e5-81da52d74bd8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 42def604-6800-4588-8a73-5991539a3e96 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe304dc1-513f-4431-9497-a1cc66773076
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 497bf133-da9a-480b-8776-1b622fd6e2d7 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a77f6fc-1a28-4649-b64f-68e8355e7657
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b02ac359-d1ee-4107-a6cb-18305753f0ab # Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ecd8874d-ff9b-409a-94e8-460abf366563
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7c8c2534-a381-4af5-918e-321a356324fa # Articles
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46b17fe9-4668-4368-8d36-75300010b000
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dd04dccc-75d1-4a21-84a0-990e892a1977
        userCondition: null
group: null
groupChildBlockTypes: true
handle: eventsBlock
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Events
sortOrder: 7
topLevel: true
