childBlocks: null
conditions: null
description: ''
enabled: true
field: 2de925e3-f1b3-474f-aa3a-8917dc160d67 # Body
fieldLayouts:
  c29a5fdf-4d7c-43d2-a36d-66ab4962017c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3fed10c6-640f-4012-aff1-a5a914e2e3ad # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 106d739c-262e-4f43-9679-d546157bc0ca
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 356fedab-a40b-492a-aeb5-a14c954d468a # Cards
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b9718b5-7ac9-4595-8f0e-4bec18a2e2d3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5b78ebed-1110-45f3-ae73-60be41813953
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: adae52e8-4cf6-4f0e-ae1d-05059dbf611f # Background grey
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7eb611e5-aca5-489b-a86b-f065a7f41488
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6b8353f0-638c-4bdf-be1b-94ec215f6520 # No spacing top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c8b5eb9-0eed-4334-9b65-6f8be0ed22ba
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 89047565-7b52-4b48-9018-8901815700b7
        userCondition: null
group: null
groupChildBlockTypes: true
handle: factsBlock
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Facts
sortOrder: 3
topLevel: true
