childBlocks: null
conditions: null
description: null
enabled: true
field: 2de925e3-f1b3-474f-aa3a-8917dc160d67 # Body
fieldLayouts:
  f4e86de3-f947-4709-ab8d-c57f8bfda1b3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 91da989b-aca3-4a36-a126-0f3223887bd4 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e023e5f7-e87f-4824-8cc2-6ba4035c7f46
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b8fabbb6-11e1-4a0a-b9a6-baae1db3524a # Tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1230988f-3a23-4ebf-a501-b8be184868f0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 42def604-6800-4588-8a73-5991539a3e96 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52abc214-f616-4087-9aa2-46ef6f1e4a95
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 497bf133-da9a-480b-8776-1b622fd6e2d7 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3308ab9-f246-4ead-934e-53458169a321
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1361e7f7-f9a4-41c7-a9a2-da753572f7ac # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d929f90f-9cd9-487e-ab49-9d33c15242ee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 174b291e-740f-4a34-a49c-d7b3dd2a07b8 # Secondary link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a58a89e6-b3b0-4401-a22a-f009b4c95e0e
            userCondition: null
            warning: null
            width: 100
        name: General
        uid: a0ca1beb-f641-4d74-8c9e-93f5379cb085
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: adc583d2-65c2-4163-99ea-8cb6887d5fb5 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 784ab6d7-4b95-4eb2-b207-f7f027b85965
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6b8353f0-638c-4bdf-be1b-94ec215f6520 # No spacing top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6192f40-eaa5-4704-938a-471b28136bc3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 168fa8bd-abcd-4636-9c11-529f65ec0c83 # Show icons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3abc7af8-4105-4f5c-9fa8-4f69438e60a9
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 201d6457-72c0-4e7c-b82f-a193ed2a6b4a
        userCondition: null
group: 238fe600-4471-43e3-865f-f2c7e82ec2ba # Hero
groupChildBlockTypes: true
handle: heroDefault
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: HeroDefault
sortOrder: 2
topLevel: true
