childBlocks: null
conditions: null
description: ''
enabled: true
field: 9b271a30-441e-4349-8015-e145efbaf982 # Content
fieldLayouts:
  dcd7e7a0-0aa8-486a-afb1-e6c12b9b4acd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3fed10c6-640f-4012-aff1-a5a914e2e3ad # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61d6d4e1-49a9-4535-a445-dc42e1623be8
            userCondition: null
            warning: null
            width: 100
        name: General
        uid: 185e1122-4052-42f7-a2ae-eb0323351ebf
        userCondition: null
group: null
groupChildBlockTypes: true
handle: imageBlock
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: image
sortOrder: 3
topLevel: true
