childBlocks: null
conditions: null
description: ''
enabled: true
field: 9b271a30-441e-4349-8015-e145efbaf982 # Content
fieldLayouts:
  2aeddce2-b942-4f4f-80df-0fef4c3c6b24:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1361e7f7-f9a4-41c7-a9a2-da753572f7ac # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9e01358-a25a-4abb-ade9-31348728ec07
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 14a640ad-7397-4ef5-bec5-c29d2a564957
        userCondition: null
group: null
groupChildBlockTypes: true
handle: linkBlock
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: link
sortOrder: 2
topLevel: true
