childBlocks: null
conditions: null
description: ''
enabled: true
field: 2de925e3-f1b3-474f-aa3a-8917dc160d67 # Body
fieldLayouts:
  56c5c841-b941-4d52-8b9e-74225aeed385:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 42def604-6800-4588-8a73-5991539a3e96 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31769b53-a5e5-4609-9588-3d763da83c5d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 497bf133-da9a-480b-8776-1b622fd6e2d7 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d22f788e-06c8-4cb4-8f79-f2ee0612506a
            userCondition: null
            warning: null
            width: 100
        name: General
        uid: 3b6c58c9-469c-46d3-8351-956d34065ee7
        userCondition: null
group: null
groupChildBlockTypes: true
handle: quoteBlock
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Quote
sortOrder: 2
topLevel: true
