childBlocks: null
conditions: null
description: ''
enabled: true
field: 2de925e3-f1b3-474f-aa3a-8917dc160d67 # Body
fieldLayouts:
  4e032e00-16e8-4cdb-aedd-c04b5d4041cf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ed8dd9c1-2fa2-4da3-bdd1-a1d2488582b8 # Quotes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38d57bfe-033a-49f7-8469-b7a8070e43d6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eadae114-7f3f-4734-b1b3-20d8b02d7a4a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: adc583d2-65c2-4163-99ea-8cb6887d5fb5 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0717a778-9377-4446-83f7-95b8e4736436
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: adae52e8-4cf6-4f0e-ae1d-05059dbf611f # Background grey
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7eb611e5-aca5-489b-a86b-f065a7f41488
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0a6ae889-cd44-4836-90c7-7eb4a7137ec5 # No spacing bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d03344b8-0855-46f2-a16b-4a9294f97459
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6b8353f0-638c-4bdf-be1b-94ec215f6520 # No spacing top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c58657c-ae94-4b59-be29-c6d1b33f4a05
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: a3cc629c-39cd-4696-8aae-816a57248c4b
        userCondition: null
group: 06936d40-6287-4cf0-9565-4ea06bbc5f23 # Body
groupChildBlockTypes: true
handle: quotesBlock
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Quotes
topLevel: true
