childBlocks: null
conditions: null
description: ''
enabled: true
field: 9b271a30-441e-4349-8015-e145efbaf982 # Content
fieldLayouts:
  ef1acb6a-3f8a-479d-93a5-489ae533a865:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 497bf133-da9a-480b-8776-1b622fd6e2d7 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb12cf57-7fc8-40a3-865a-d30dc4cb9aaa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 45035e26-3f4c-4339-b3a4-f681dab47429
        userCondition: null
group: null
groupChildBlockTypes: true
handle: textBlock
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: text
sortOrder: 1
topLevel: true
