childBlocks: null
conditions: null
description: null
enabled: true
field: 2de925e3-f1b3-474f-aa3a-8917dc160d67 # Body
fieldLayouts:
  f2fce118-2d36-49b8-9734-5cb64cc01db6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 42def604-6800-4588-8a73-5991539a3e96 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b82387d7-0618-4fc7-a1b6-1f8dc67af2d8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 497bf133-da9a-480b-8776-1b622fd6e2d7 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e577c16-cbeb-441c-b06a-408c55a470f0
            userCondition: null
            warning: null
            width: 100
        name: General
        uid: 71f26f11-63f6-4d65-b5a0-a7e966b282a6
        userCondition: null
group: null
groupChildBlockTypes: true
handle: textBlock
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Text
sortOrder: 1
topLevel: true
