fieldLayouts:
  b3cf0a3f-67d6-457d-9b4a-78bb316b7f57:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 00509a8b-d372-487e-96ba-4b0a0c6eb638
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 15b10ff3-3e93-44ec-8f78-fe514968ab61
        userCondition: null
fs: icons
handle: icons
name: Icons
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
