childBlocks: null
conditions: null
description: ''
enabled: true
field: 2de925e3-f1b3-474f-aa3a-8917dc160d67 # Body
fieldLayouts:
  80fdeb3a-71e1-4d0e-b773-8b858f075cfd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0a6ae889-cd44-4836-90c7-7eb4a7137ec5 # No spacing bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01e2535d-8697-42d6-bbb0-62e9e1b467f9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6b8353f0-638c-4bdf-be1b-94ec215f6520 # No spacing top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e24fa47a-265b-41f4-8363-a51c33070a71
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 02af3931-3fd9-49ac-a6e5-03359af2c58f
        userCondition: null
group: 06936d40-6287-4cf0-9565-4ea06bbc5f23
groupChildBlockTypes: true
handle: albumBlock
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Album
topLevel: true
