columnSuffix: cvohfsbi
contentColumnType: string
fieldGroup: b02c6922-dfa1-4396-abfe-a3692bc842b0 # Common
handle: commonColor
instructions: null
name: Color
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - rose
        -
          - value
          - rose
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - violet
        -
          - value
          - violet
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - lavendel
        -
          - value
          - lavendel
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - blue
        -
          - value
          - blue
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - green
        -
          - value
          - primary
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - black
        -
          - value
          - black
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - white
        -
          - value
          - white
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
