columnSuffix: null
contentColumnType: string
fieldGroup: b02c6922-dfa1-4396-abfe-a3692bc842b0 # Common
handle: commonVakken
instructions: null
name: Vakken
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: null
  showSiteMenu: true
  sources:
    - 'section:ceb21329-439a-4697-8cb3-c475786b9a24' # Vakken
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
