columnSuffix: fmwrqryb
contentColumnType: string
handle: commonMail
instructions: null
name: Mail
searchable: false
settings:
  placeholder: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
