columnSuffix: null
contentColumnType: string
handle: commonLinks
instructions: null
name: Links
searchable: false
settings:
  entryTypes:
    -
      handle: linkBlock
      uid: 55ca2b04-e644-4417-896c-e6f387111f47
    -
      uid: f62465ee-64f8-4666-b7ba-47d87de3cbcc
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
