columnSuffix: dkekmxkh
contentColumnType: text
handle: commonIntroduction
instructions: null
name: Introduction
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 954a0594-9557-4cc8-bc11-354692af5b75 # Simple
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
