columnSuffix: null
contentColumnType: string
fieldGroup: b02c6922-dfa1-4396-abfe-a3692bc842b0 # Common
handle: commonSecondaryLinks
instructions: null
name: 'Secondary Links'
searchable: false
settings:
  contentTable: '{{%matrixcontent_commonsecondarylinks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
