columnSuffix: null
contentColumnType: string
handle: commonQuotes
instructions: null
name: Quotes
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:e0199469-522e-4e9c-8fd4-33a017c3b94a' # Quotes
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
