columnSuffix: null
contentColumnType: string
handle: commonNumbers
instructions: null
name: Numbers
searchable: false
settings:
  entryTypes:
    -
      uid: e403b4c4-8fa5-44c8-842e-7c89e678f7e7
  maxEntries: 0
  minEntries: 0
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
