columnSuffix: null
contentColumnType: string
handle: commonSecondaryLinks
instructions: null
name: 'Secondary Links'
searchable: false
settings:
  entryTypes:
    -
      handle: linkBlock
      uid: 5dde7fd6-5629-4f13-9298-5d323b2efaae
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
