columnSuffix: kuavgjkz
contentColumnType: boolean
fieldGroup: b02c6922-dfa1-4396-abfe-a3692bc842b0 # Common
handle: commonBackgroundGray
instructions: null
name: 'Background grey'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
