columnSuffix: null
contentColumnType: string
fieldGroup: b02c6922-dfa1-4396-abfe-a3692bc842b0 # Common
handle: commonBody
instructions: null
name: Body
searchable: false
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  minLevels: null
  minTopBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
