columnSuffix: mjndizwf
contentColumnType: boolean
handle: commonNoSpacingBottom
instructions: null
name: 'No spacing bottom'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
