columnSuffix: kuavgjkz
contentColumnType: boolean
handle: commonBackgroundGray
instructions: null
name: 'Background grey'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
