fieldLayouts:
  7a05592f-59fa-4d23-89c2-33728da62e15:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e96245eb-37d4-475a-98ca-82ebcd5f62bc # Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a28bfd0b-c31e-47ee-9ac6-e7dfc0c91100
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 11aa3d74-6507-4456-9814-266b32e421a3 # Phone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a520aba-f007-406e-b045-f8eb02538b15
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1a83051b-5fff-4173-99ff-a16698a69da9 # Mail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1427bdd1-8ffc-4b7d-b7ba-e0fd1ee91093
            userCondition: null
            warning: null
            width: 100
        name: General
        uid: d18921a9-551f-4f55-9ac6-02c4287197cf
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5994f1c4-513f-444d-98dd-a5a111b1b594 # Footer column
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 541537b2-085d-4a42-83e7-36f21657943d
            userCondition: null
            warning: null
            width: 100
        name: 'Main navigation'
        uid: 1fb8a716-c7c8-469f-aac0-62f9aacb99c1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 79f2f6d9-11d4-45d2-87f2-a1e7079ede77 # Secondary Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec6e1ef0-9de8-4b01-bf85-ec463de99d74
            userCondition: null
            warning: null
            width: 100
        name: 'Secondary navigation'
        uid: b271e3a2-36dd-4dfa-ab16-b47025e7a6e4
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
