fieldLayouts:
  6090e98c-c4d6-47fb-9827-eab591c02f50:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 92e56108-7d63-4d93-b353-6bfed2351e0d # Main menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f9df7f6-efeb-4693-a407-6cf2e9729a0a
            userCondition: null
            warning: null
            width: 100
        name: General
        uid: c34d2f44-47a7-462c-83a2-60f9a382ff4c
        userCondition: null
handle: header
name: Header
sortOrder: 1
