defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: default
    uid: 4f313438-37e8-461a-9c66-219cbed21a6d # Default
handle: album
maxAuthors: 1
name: Album
propagationMethod: all
siteSettings:
  520ae88b-24db-491f-a50d-9ec2cb2dc5b5: # Mai
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
