defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b34da8dd-bc1c-4a58-bec8-6905e3ef312b # Default
handle: article
maxAuthors: 1
name: Article
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  520ae88b-24db-491f-a50d-9ec2cb2dc5b5: # Mai
    enabledByDefault: true
    hasUrls: true
    template: pages/article.twig
    uriFormat: 'blog/{slug}'
type: channel
