defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: default
    uid: 649ea460-26ca-49d6-9270-7345c048c93a # Default
handle: cards
maxAuthors: 1
name: Cards
propagationMethod: all
siteSettings:
  520ae88b-24db-491f-a50d-9ec2cb2dc5b5: # Mai
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
