defaultPlacement: end
enableVersioning: true
handle: evenementen
name: Evenementen
propagationMethod: all
siteSettings:
  520ae88b-24db-491f-a50d-9ec2cb2dc5b5: # Mai
    enabledByDefault: true
    hasUrls: true
    template: evenementen/_entry
    uriFormat: 'evenementen/{slug}'
type: channel
