defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f650ff39-b930-480c-95f1-c651efdaacd6 # Default
handle: evenementen
maxAuthors: 1
name: Evenementen
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  520ae88b-24db-491f-a50d-9ec2cb2dc5b5: # Mai
    enabledByDefault: true
    hasUrls: true
    template: pages/evenement.twig
    uriFormat: 'evenementen/{slug}'
type: channel
