defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 928188f5-5f18-49f8-8686-a8909488ee22 # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  520ae88b-24db-491f-a50d-9ec2cb2dc5b5: # Mai
    enabledByDefault: true
    hasUrls: true
    template: pages/index.twig
    uriFormat: __home__
type: single
