defaultPlacement: end
enableVersioning: true
handle: leerkracht
name: Leerkracht
propagationMethod: all
siteSettings:
  520ae88b-24db-491f-a50d-9ec2cb2dc5b5: # Mai
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 1dc92c5f-6862-404c-a350-b8a72da624f7
type: structure
