defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: default
    uid: daf4a979-115d-4d8d-aa10-8c448cbc2876 # Default
handle: navcolumns
maxAuthors: 1
name: NavColumns
propagationMethod: all
siteSettings:
  520ae88b-24db-491f-a50d-9ec2cb2dc5b5: # Mai
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
