defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 0b75516d-23a5-4817-9c75-0c4c06368a53 # Default
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  520ae88b-24db-491f-a50d-9ec2cb2dc5b5: # Mai
    enabledByDefault: true
    hasUrls: true
    template: pages/detail.twig
    uriFormat: '{slug}'
structure:
  maxLevels: 3
  uid: df3f3b31-00ac-4850-bb86-cfdc3d691e67
type: structure
