defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: default
    uid: 3008fa68-cbfa-4a59-aaa7-c3ebdd0452d2 # Default
handle: quotes
maxAuthors: 1
name: Quotes
propagationMethod: all
siteSettings:
  520ae88b-24db-491f-a50d-9ec2cb2dc5b5: # Mai
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
