defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: default
    uid: 07c3457b-b52b-4825-82ad-7c77be131f59 # Default
handle: tab
maxAuthors: 1
name: Tab
propagationMethod: all
siteSettings:
  520ae88b-24db-491f-a50d-9ec2cb2dc5b5: # Mai
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
