defaultPlacement: end
enableVersioning: true
handle: tab
name: Tab
propagationMethod: all
siteSettings:
  520ae88b-24db-491f-a50d-9ec2cb2dc5b5: # Mai
    enabledByDefault: true
    hasUrls: true
    template: tab/_entry
    uriFormat: 'tab/{slug}'
type: channel
