defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: default
    uid: 476a6690-2335-460e-86cd-296e06c0a0cd # Default
handle: vakken
maxAuthors: 1
name: Vakken
propagationMethod: all
siteSettings:
  520ae88b-24db-491f-a50d-9ec2cb2dc5b5: # Mai
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
